version: '3'
services:
  # Django web server
  web:
    image: web:local
    build:
      context: ./django
      dockerfile: Dockerfile
    hostname: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  # Postgres
  db:
    image: postgres:15-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
      image: redis:7-alpine3.18
      hostname: redis

  # React app
  app:
    image: app:local
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app/
      - /app/node_modules
    ports:
      - "3000:3000"

  api-caller:
    build: 
      context: ./django
      dockerfile: Dockerfile
    command: python manage.py make_api_calls --interval 5
    depends_on:
      - web
      - db
      - redis
    volumes:
      - ./django:/app

  websocket:
    image: web:local
    build:
      context: ./django
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 8001 casestudy.asgi:application
    volumes:
      - ./django:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=casestudy.settings
    tty: true
    stdin_open: true

volumes:
    postgres_data:
