# Generated by Django 4.2 on 2025-04-11 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casestudy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('securities', models.ManyToManyField(blank=True, related_name='watchlists', to='casestudy.security')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='casestudy.security')),
            ],
        ),
        migrations.AddIndex(
            model_name='userwatchlist',
            index=models.Index(fields=['user'], name='casestudy_u_user_id_d732c0_idx'),
        ),
        migrations.AddIndex(
            model_name='userwatchlist',
            index=models.Index(fields=['user', 'created_at'], name='casestudy_u_user_id_8f7663_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userwatchlist',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='securitypricehistory',
            index=models.Index(fields=['security', 'date'], name='casestudy_s_securit_5f18bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='securitypricehistory',
            unique_together={('security', 'date')},
        ),
    ]
